sd21/its/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from its import views
from django.views.generic import ListView, DetailView
from its.models import Product

urlpatterns = patterns('',
   # 問い合わせ
   url(r'^incident/$', views.incident_list, name='incident_list'),
   url(r'^incident/add$', views.incident_edit, name='incident_add'),
   url(r'^incident/mod/(?P<incident_id>\d+)/$', views.incident_edit, name='incident_mod'),                    
   url(r'^incident/del/(?P<incident_id>\d+)/$', views.incident_del, name='incident_del'),
   # 対応
   url(r'^support/(?P<incident_id>\d+)/$', views.SupportList.as_view(), name='support_list'),
   url(r'^support/add/(?P<incident_id>\d+)/$', views.support_edit, name='support_add'),
   url(r'^support/mod/(?P<incident_id>\d+)/(?P<support_id>\d+)/$', views.support_edit, name='support_mod'),
   url(r'^support/del/(?P<incident_id>\d+)/(?P<support_id>\d+)/$', views.support_del, name='support_del'),
   # 製品
   url(r'^product/$',
       ListView.as_view(
                        model=Product,
                        queryset=Product.objects.all().order_by('id'),
                        context_object_name='product_list',
                        template_name='its/product_list.html'
        )
   ),
   
   
   
                          
)

sd21/sd21/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sd21.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^its/', include('its.urls', namespace='its')),
)

sd21/its/models.py
# -*- coding: utf-8 -*-
from django.db import models
#from django.db.models.fields import BLANK_CHOICE_DASH
from django.utils import timezone
from django.forms import ModelForm

class Product(models.Model):
    '''製品'''
    #inventry = models.ForeignKey(Inventry, verbose_name=u'資産', related_name='inventries')
    name = models.CharField(u'製品名', max_length=255)
    maker = models.CharField(u'メーカー', max_length=255, blank=True)
    lot = models.IntegerField(u'ロット' , blank=True, default=1)
    cpu = models.CharField('CPU', max_length=255, blank=True)
    memory = models.CharField('メモリ', max_length=255, blank=True)
    hdd = models.CharField('hdd', max_length=255, blank=True)
    warranty = models.CharField(u'ハードウェア保証', max_length=255, blank=True)
    memo = models.TextField(u'メモ', blank=True)
    
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = u'製品'            #adminサイトの表示変更
        verbose_name_plural = '製品一覧'    #adminサイトの表示変更
        

class Location(models.Model):
    '''場所'''
    name = models.CharField(u'名称', max_length=255, unique=True)
    short_name = models.CharField(u'略称', max_length=255, unique=True)
    segment = models.CharField(u'セグメント', max_length=255, unique=True)
    shop_no = models.CharField(u'店舗番号', max_length=255, blank=True)
    address = models.CharField(u'住所', max_length=255, blank=True)
    tel = models.CharField(u'TEL', max_length=255, blank=True)
    fax = models.CharField(u'FAX', max_length=255, blank=True)
    area = models.CharField(u'地区', max_length=255, blank=True)
    
    def __str__(self):
        return self.short_name
    
    class Meta:
        verbose_name = u'場所'
        verbose_name_plural = u'場所一覧'


    
class Inventry(models.Model):
    '''資産'''
    product = models.ForeignKey(Product, verbose_name=u'製品', related_name='products')
    location = models.ForeignKey(Location, verbose_name='場所', related_name='locations')
    name = models.CharField(u'シリアルナンバー', unique=True, max_length=255)
    user = models.CharField(u'使用者', max_length=255, blank=True)
    #location = models.CharField(u'場所', max_length=255, blank=True)
    pc_name = models.CharField(u'PC名', max_length=255, blank=True)
    pc_category = models.CharField(u'PC種別', max_length=255, blank=True)
    os = models.CharField(u'OS', max_length=255, blank=True)
    msoffice = models.CharField(u'MS Offie', max_length=255, blank=True)
    warranty_from = models.DateField(u'保証開始日', blank=True, null=True)
    warranty_to = models.DateField(u'保証満了日', blank=True, null=True)
    
    def __str__(self):
        return self.pc_name
    
    class Meta:
        verbose_name = u'IT資産'          #adminサイトの表示変更
        verbose_name_plural = u'IT資産一覧'     #adminサイトの表示変更

class Incident(models.Model):
    '''コール受付'''
    ENTRY_TYPE = (
        (u'TEL', u'TEL'),
        (u'直接', u'直接（口頭）'),
        (u'Eメール', u'Eメール'),
        (u'監視', u'監視'),
    )
        

    STATUS_TYPE = (
        (u'受付', u'受付'),
        (u'対応中', u'対応中'),
        (u'対応済み', u'対応済み'),
        (u'完了', u'完了'),
    )
    
    
    
    datetime = models.DateTimeField(u'受付日時' )
    #entry_date = models.DateField(u'受付日')
    #entry_time = models.TimeField(u'受付時間')
    entry_type = models.CharField(u'問い合わせ種別', max_length=255, choices=ENTRY_TYPE) 
    location = models.ForeignKey(Location, verbose_name='場所', related_name='incident_locations')
    inventry = models.ForeignKey(Inventry, blank=True, null=True, verbose_name='PC', related_name='incident_Inventries')
    client = models.CharField(u'依頼者', max_length=255, blank=True)
    contact = models.CharField(u'連絡者', max_length=255, blank=True)
    title = models.CharField(u'件名',max_length=255,)
    content = models.TextField(u'内容')
    status = models.CharField(u'ステータス', max_length=255, choices=STATUS_TYPE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = u'問い合わせ'          #adminサイトの表示変更
        verbose_name_plural = u'問い合わせ一覧'     #adminサイトの表示変更


class Support(models.Model):
    incident = models.ForeignKey(Incident, verbose_name='問い合わせ', related_name='incident_support')
    datetime_from = models.DateTimeField(u'対応開始日時' )
    datetime_to = models.DateTimeField(u'対応終了日時' )
    comment = models.TextField(u'対応内容')

    def __str__(self):
        return self.comment

    class Meta:
        verbose_name = u'対応'          #adminサイトの表示変更
        verbose_name_plural = u'対応一覧'     #adminサイトの表示変更

sd21/its/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm, widgets
from bootstrap3_datetime.widgets import DateTimePicker
from its.models import Incident, Support
from django.core.cache.backends.db import Options
from django import forms as forms


class SearchForm(forms.Form):
    keyword = forms.CharField(label="キーワード")

class IncidentSearchForm(forms.Form):
    keyword = forms.CharField(label=u"キーワード")




class IncidentForm(ModelForm):
    '''問い合わせのフォーム'''
    class Meta:
        model = Incident

        widgets = {
            'datetime': DateTimePicker(options={"format": "YYYY-MM-DD HH:mm"}),
                   }
        #keyword = forms.CharField(u'キーワード', max_length=255)
        fields = ('datetime', 'entry_type', 'location', 'client', 'contact', 'title', 'content', 'status',)
        
class SupportForm(ModelForm):
    '''対応のフォーム'''
    class Meta:
        model = Support
        
        widgets = {
            'datetime_from': DateTimePicker(options ={"format": "YYYY-MM-DD HH:mm", "showToday": True}),
            'datetime_to': DateTimePicker(options={"format": "YYYY-MM-DD HH:mm"}),
                   }
        
        fields = ('datetime_from', 'datetime_to', 'comment',)

sd21/its/views.py
# -*- coding: utf-8 -*-
#from django.shortcuts import render
from django.http.response import HttpResponse
from django.core.context_processors import request
from django.template import RequestContext
from its.forms import IncidentForm, SupportForm
from its.models import Incident, Support
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.views.generic.list import ListView
from its.forms import IncidentSearchForm

def incident_list(request):
    '''問い合わせの一覧'''
#    return HttpResponse(u'問い合わせ一覧')
    form = IncidentSearchForm()
    if request.method == 'GET':
        
        incidents = Incident.objects.all().order_by('id')
        return render_to_response('its/incident_list.html',
                              #{'incidents': incidents},
                              dict(incidents=incidents),
                              context_instance=RequestContext(request))

    elif request.method == 'POST':
        form = IncidentSearchForm(request.POST)
        incidents = Incident.objects.all()
        if form.is_valid:
            incidents = incidents.filter()

    return render_to_response('search.html',
                              {'form': form, 'incidents': incidents},
                              context_instance=RequestContext(request))


def incident_edit(request, incident_id=None):
    '''問い合わせの編集'''
    #return HttpResponse(u'問い合わせの編集')
    if incident_id:         #incident_idが指定されている（修正時）
        incident = get_object_or_404(Incident, pk=incident_id)
    else:                   # incident_idが指定されていない（追加時）
        incident = Incident()
    
    if request.method == 'POST':
        form = IncidentForm(request.POST, instance=incident)
        if form.is_valid():
            incident = form.save(commit=False)
            incident.save()
            return redirect('its:incident_list')
    else:   # GETの時
        form =IncidentForm(instance=incident)       # インスタンスからフォームを作成
        
    return render_to_response('its/incident_edit.html',
                              dict(form=form, incident_id=incident_id),
                              context_instance=RequestContext(request))
    
#def search_incident(request, incident=None):
    
        

def incident_del(request, incident_id):
    '''問い合わせの削除'''
    #return HttpResponse(u'問い合わせの削除')
    incident = get_object_or_404(Incident, pk=incident_id)
    incident.delete()
    return redirect('its:incident_list')

class SupportList(ListView):
    '''作業の一覧'''
    context_object_name = 'supports'
    template_name = 'cms/support_list.html'
    paginate_by = 2

    def get(self, request, *args, **kwargs):
        incident = get_object_or_404(Incident, pk=kwargs['incident_id'])
        supports = incident.incident_support.all().order_by('id')
        self.object_list = supports

        context = self.get_context_data(object_list=self.object_list, incident=incident)
        return self.render_to_response(context)


def support_edit(request, incident_id, support_id=None):
    '''作業の編集'''
    incident = get_object_or_404(Incident, pk=incident_id)
    if support_id:
        support = get_object_or_404(Support, pk=support_id)
    else:
        support = Support()
        
    if request.method == 'POST':
        form = SupportForm(request.POST, instance=support)
        if form.is_valid():
            support = form.save(commit=False)
            support.incident = incident
            support.save()
            return redirect('its:support_list', incident_id=incident_id)
    else:
        form = SupportForm(instance=support)
    
    return render_to_response('its/support_edit.html',
                              dict(form=form, incident_id=incident_id, support_id=support_id),
                              context_instance=RequestContext(request))


def support_del(request, incident_id, support_id):
    '''作業の削除'''
    support = get_object_or_404(Support, pk=support_id)
    support.delete()
    return redirect('its:support_list', incident_id=incident_id)

sd21/its/templates/its/incident_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}問い合わせの編集{% endblock title %}

{% block content %}
    <h3 class="page-header">問い合わせの編集</h3>
    {% if incident_id %}
    <form action="{% url 'its:incident_mod' incident_id=incident_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'its:incident_add' %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'its:incident_list' %}" class="btn btn-default btn-sm">戻る</a>
{% endblock content %}

sd21/its/templates/its/incident_list.html
{% extends "base.html" %}

{% block title %}問い合わせ一覧{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">問い合わせの一覧</h3>
    {{ keyword }}
    {% include "search.html" %}
    
    <a href="{% url 'its:incident_add' %}" class="btn btn-default btn-sm">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>ステータス</th>
          <th>受付日時</th>
          <th>受付種別</th>
          <th>場所</th>
          <th>依頼者</th>
          <th>連絡者</th>
          <th>件名</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        {% for incident in incidents %}
        <tr>
          <td>{{ incident.id }}</td>
          <td>{{ incident.status }}</td>
          <td>{{ incident.datetime|date:"Y年Md日 H:m" }}</td>
          <td>{{ incident.entry_type }}</td>
          <td>{{ incident.location }}</td>
          <td>{{ incident.client }}</td>
          <td>{{ incident.contact }}</td>
          <td>{{ incident.title }}</td>
          <td>
            <a href="{% url 'its:incident_mod' incident_id=incident.id %}" class="btn btn-default btn-sm">修正</a>
            <a href="{% url 'its:incident_del' incident_id=incident.id %}" class="btn btn-default btn-sm">削除</a>
            <a href="{% url 'its:support_list' incident_id=incident.id %}" class="btn btn-default btn-sm btn-primary">対応の一覧</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock content %}

sd21/its/templates/its/product_list.html
{% extends "base.html" %}

{% block content %}
    <h2>製品一覧</h2>
    <ul>
        {% for data in object_list %}
            <li>{{ data.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}

sd21/its/templates/its/support_edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}対応の編集{% endblock title %}

{% block content %}
    <h3 class="page-header">対応の編集</h3>
    {% if support_id %}
    <form action="{% url 'its:support_mod' incident_id=incident_id support_id=support_id %}" method="post" class="form-horizontal" role="form">
    {% else %}
    <form action="{% url 'its:support_add' incident_id=incident_id %}" method="post" class="form-horizontal" role="form">
    {% endif %}
      {% csrf_token %}
      {{ form|bootstrap_horizontal }}
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'its:support_list' incident_id=incident_id %}" class="btn btn-default btn-sm">戻る</a>
{% endblock content %}

sd21/its/templates/its/support_list.html
{% extends "base.html" %}

{% block title %}対応の一覧{% endblock title %}

{% block extrahead %}
<script>
$(function() {
  $('.del_confirm').on('click', function(){
	$("#del_pk").text($(this).attr("pk"));  
	$('#del_url').attr('href', $(this).attr("url"));
	  
  });
});
</script>
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">対応の一覧 <small>{{ incident.name }}</small></h3>
    <a href="{% url 'its:support_add' incident_id=incident.id %}" class="btn btn-default btn-sm">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>対応開始日時</th>
          <th>対応終了日時</th>
          <th>対応内容</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        {% for support in supports %}
        <tr>
          <td>{{ support.id }}</td>
          <td>{{ support.datetime_from|date:"Y年Md日 H:m" }}</td>
          <td>{{ support.datetime_to|date:"Y年Md日 H:m" }}</td>
          <td>{{ support.comment }}</td>
          <td>
            <a href="{% url 'its:support_mod' incident_id=incident.id support_id=support.id %}" class="btn btn-default btn-sm">修正</a>
            <button url="{% url 'its:support_del' incident_id=incident.id support_id=support.id %}" class="btn btn-default btn-sm del_confirm" data-toggle="modal" data-target="#deleteModal" pk="{{ support.id }}">削除</button>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    
    {% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&laquo;</a>
      {% endif %}
      {% for linkpage in page_obj.paginator.page_range %}
        {% ifequal linkpage page_obj.number %}
          <li class="active"><a href="#">{{ linkpage }}</a></li>
        {% else %}
          <li><a href="?page={{ linkpage }}">{{ linkpage }}</a></li>
        {% endifequal %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><a href="#">&raquo;</a></li>
      {% endif %}
    </ul>
    {% endif %}
    <div>
      <a href="{% url 'its:incident_list' %}" class="btn btn-default btn-sm">戻る</a>
    </div>
{# 削除を確認するモーダル　ダイアログ #}
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="deleteModalLabel">確認</h4>
          </div>
          <div class="modal-body">
            <p>ID: <span id="del_pk"></span>を削除しますか？</p>
          </div>
          <div class="modal-footer">
            <a href="#" class="btn btn-primary" id="del_url">OK</a>
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>      
          </div>
        </div>
      </div>
    </div>
{% endblock content %}
